"""Add capacity_mwp and pvlive_updated_utc columns to gsp_yield

Revision ID: 14878f62c6d1
Revises: d92996388b65
Create Date: 2023-06-23 13:47:29.240019

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14878f62c6d1"
down_revision = "d92996388b65"
branch_labels = None
depends_on = None


def upgrade(): # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gsp_yield", sa.Column("capacity_mwp", sa.Float(), nullable=True))
    op.add_column("gsp_yield", sa.Column("pvlive_updated_utc", sa.DateTime(), nullable=True))
    op.alter_column("location", "gsp_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "metric_value",
        "value",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "metric_value", "number_of_data_points", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade(): # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "metric_value", "number_of_data_points", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "metric_value",
        "value",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("location", "gsp_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("gsp_yield", "pvlive_updated_utc")
    op.drop_column("gsp_yield", "capacity_mwp")
    # ### end Alembic commands ###
