"""Add lots of indexes

Revision ID: 76716e17eff7
Revises: a6fb75892950
Create Date: 2023-09-07 11:53:51.146798

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76716e17eff7"
down_revision = "a6fb75892950"
branch_labels = None
depends_on = None


def upgrade(): # noqa:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_api_request_created_utc"), "api_request", ["created_utc"], unique=False
    )
    op.drop_index("ix_datetime_interval_end_datetime_utc", table_name="datetime_interval")
    op.create_index(
        op.f("ix_datetime_interval_end_datetime_utc"),
        "datetime_interval",
        ["end_datetime_utc"],
        unique=False,
    )
    op.drop_index("ix_datetime_interval_start_datetime_utc", table_name="datetime_interval")
    op.create_index(
        op.f("ix_datetime_interval_start_datetime_utc"),
        "datetime_interval",
        ["start_datetime_utc"],
        unique=False,
    )
    op.create_index("idx_forecast_created_utc", "forecast", ["created_utc"], unique=False)
    op.create_index("index_forecast_historic", "forecast", ["historic"], unique=False)
    op.create_index(op.f("ix_forecast_created_utc"), "forecast", ["created_utc"], unique=False)

    op.create_index(
        op.f("ix_forecast_value_created_utc"), "forecast_value", ["created_utc"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_value_last_seven_days_created_utc"),
        "forecast_value_last_seven_days",
        ["created_utc"],
        unique=False,
    )
    op.create_foreign_key(
        None, "forecast_value_last_seven_days", "forecast", ["forecast_id"], ["id"]
    )
    op.create_index(
        op.f("ix_forecast_value_latest_created_utc"),
        "forecast_value_latest",
        ["created_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_value_old_created_utc"),
        "forecast_value_old",
        ["created_utc"],
        unique=False,
    )
    op.create_index(op.f("ix_gsp_yield_created_utc"), "gsp_yield", ["created_utc"], unique=False)
    op.create_index(
        op.f("ix_input_data_last_updated_created_utc"),
        "input_data_last_updated",
        ["created_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_value_created_utc"), "metric_value", ["created_utc"], unique=False
    )
    op.create_index(op.f("ix_status_created_utc"), "status", ["created_utc"], unique=False)
    # ### end Alembic commands ###


def downgrade(): # noqa:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_status_created_utc"), table_name="status")
    op.drop_index(op.f("ix_metric_value_created_utc"), table_name="metric_value")
    op.drop_index(
        op.f("ix_input_data_last_updated_created_utc"), table_name="input_data_last_updated"
    )
    op.drop_index(op.f("ix_gsp_yield_created_utc"), table_name="gsp_yield")
    op.drop_index(op.f("ix_forecast_value_old_created_utc"), table_name="forecast_value_old")
    op.drop_index(op.f("ix_forecast_value_latest_created_utc"), table_name="forecast_value_latest")
    op.drop_constraint(None, "forecast_value_last_seven_days", type_="foreignkey")
    op.drop_index(
        op.f("ix_forecast_value_last_seven_days_created_utc"),
        table_name="forecast_value_last_seven_days",
    )
    op.drop_index("ix_forecast_value_created_utc", table_name="forecast_value")
    op.drop_index(op.f("ix_forecast_created_utc"), table_name="forecast")
    op.drop_index("index_forecast_historic", table_name="forecast")
    op.drop_index("idx_forecast_created_utc", table_name="forecast")
    op.drop_index(op.f("ix_datetime_interval_start_datetime_utc"), table_name="datetime_interval")
    op.create_index(
        "ix_datetime_interval_start_datetime_utc",
        "datetime_interval",
        [sa.text("start_datetime_utc DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_datetime_interval_end_datetime_utc"), table_name="datetime_interval")
    op.create_index(
        "ix_datetime_interval_end_datetime_utc",
        "datetime_interval",
        [sa.text("end_datetime_utc DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_api_request_created_utc"), table_name="api_request")
    # ### end Alembic commands ###
