"""empty message

Revision ID: 820c16a0524c
Revises: e8654d87379b
Create Date: 2025-05-02 16:06:12.041997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820c16a0524c'
down_revision = 'e8654d87379b'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrades the database schema to the next revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrades the database schema to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'created_utc')
    # ### end Alembic commands ###
