"""Adjust MetricValue

Revision ID: 848c1673e7be
Revises: 3e6942391f0c
Create Date: 2022-09-05 16:23:05.072073

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "848c1673e7be"
down_revision = "3e6942391f0c"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metric_value", sa.Column("forecast_horizon_minutes", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric_value", "forecast_horizon_minutes")
    # ### end Alembic commands ###
