"""empty message

Revision ID: 870afe3b2b8d
Revises: f4bb5237f428
Create Date: 2022-05-09 12:47:37.931766

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "870afe3b2b8d"
down_revision = "f4bb5237f428"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("location", sa.Column("installed_capacity_mw", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "installed_capacity_mw")
    # ### end Alembic commands ###
