"""
Add forecast latest table

Revision ID: 8eb6900d2e80
Revises: 033bf0f2eaef
Create Date: 2022-05-26 07:50:23.497661

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8eb6900d2e80'
down_revision = '033bf0f2eaef'
branch_labels = None
depends_on = None


def upgrade(): # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_value_latest',
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('gsp_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('target_time', 'gsp_id')
    )
    op.create_index(op.f('ix_forecast_value_latest_forecast_id'), 'forecast_value_latest', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecast_value_latest_gsp_id'), 'forecast_value_latest', ['gsp_id'], unique=False)
    op.create_index(op.f('ix_forecast_value_latest_target_time'), 'forecast_value_latest', ['target_time'], unique=False)
    op.create_index('uix_1', 'forecast_value_latest', ['gsp_id', 'target_time'], unique=True, postgresql_where=sa.text('is_primary'))
    op.add_column('forecast', sa.Column('historic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade(): # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'historic')
    op.drop_index('uix_1', table_name='forecast_value_latest', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_forecast_value_latest_target_time'), table_name='forecast_value_latest')
    op.drop_index(op.f('ix_forecast_value_latest_gsp_id'), table_name='forecast_value_latest')
    op.drop_index(op.f('ix_forecast_value_latest_forecast_id'), table_name='forecast_value_latest')
    op.drop_table('forecast_value_latest')
    # ### end Alembic commands ###
