"""Add properties column to forecast_value

Revision ID: a6fb75892950
Revises: 08ba6879b865
Create Date: 2023-07-03 11:00:31.216789

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a6fb75892950"
down_revision = "08ba6879b865"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("forecast_value", sa.Column("properties", sa.JSON(), nullable=True))
    op.add_column(
        "forecast_value_last_seven_days", sa.Column("properties", sa.JSON(), nullable=True)
    )
    op.add_column("forecast_value_latest", sa.Column("properties", sa.JSON(), nullable=True))
    op.add_column("forecast_value_old", sa.Column("properties", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forecast_value_old", "properties")
    op.drop_column("forecast_value_latest", "properties")
    op.drop_column("forecast_value_last_seven_days", "properties")
    op.drop_column("forecast_value", "properties")

    # ### end Alembic commands ###
