""" Add p_level to metric_value

Revision ID: c74d778923e9
Revises: ed4a2f8c030a
Create Date: 2023-10-02 13:44:28.142008

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c74d778923e9"
down_revision = "ed4a2f8c030a"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metric_value", sa.Column("p_level", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric_value", "p_level")
    # ### end Alembic commands ###
