"""empty message

Revision ID: d4c688511bf9
Revises: 26435baa2929
Create Date: 2022-11-14 18:56:23.171628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4c688511bf9'
down_revision = '26435baa2929'
branch_labels = None
depends_on = None


def upgrade(): # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_value_last_seven_days',
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(precision=6), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    # ### end Alembic commands ###


def downgrade(): # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_value_last_seven_days')
    # ### end Alembic commands ###
