"""empty message

Revision ID: d92996388b65
Revises: caea7b5cf249
Create Date: 2023-05-11 15:07:43.373248

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d92996388b65"
down_revision = "caea7b5cf249"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "uuid", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "api_request",
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "uuid", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("user_uuid", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_api_request_user_uuid"), "api_request", ["user_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_request_user_uuid"), table_name="api_request")
    op.drop_table("api_request")
    op.drop_table("user")
    # ### end Alembic commands ###
