"""Added the 'intialization_datetime_utc' column to the Forecast 

Revision ID: e8654d87379b
Revises: 06ced43c1321
Create Date: 2025-04-04 10:36:05.633619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8654d87379b'
down_revision = '06ced43c1321'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrades the database schema to the next revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('initialisation_datetime_utc', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrades the database schema to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'initialisation_datetime_utc')
    # ### end Alembic commands ###
