"""empty message

Revision ID: ea79f7472cc5
Revises: 16ced43c1321
Create Date: 2024-12-09 16:26:49.560239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea79f7472cc5'
down_revision = '16ced43c1321'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrades the database schema to the next revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_value_2025_01',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_01_created_utc_idx', 'forecast_value_2025_01', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_01_forecast_id_idx', 'forecast_value_2025_01', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_01_target_time_idx', 'forecast_value_2025_01', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_02',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_02_created_utc_idx', 'forecast_value_2025_02', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_02_forecast_id_idx', 'forecast_value_2025_02', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_02_target_time_idx', 'forecast_value_2025_02', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_03',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_03_created_utc_idx', 'forecast_value_2025_03', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_03_forecast_id_idx', 'forecast_value_2025_03', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_03_target_time_idx', 'forecast_value_2025_03', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_04',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_04_created_utc_idx', 'forecast_value_2025_04', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_04_forecast_id_idx', 'forecast_value_2025_04', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_04_target_time_idx', 'forecast_value_2025_04', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_05',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_05_created_utc_idx', 'forecast_value_2025_05', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_05_forecast_id_idx', 'forecast_value_2025_05', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_05_target_time_idx', 'forecast_value_2025_05', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_06',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_06_created_utc_idx', 'forecast_value_2025_06', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_06_forecast_id_idx', 'forecast_value_2025_06', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_06_target_time_idx', 'forecast_value_2025_06', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_07',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_07_created_utc_idx', 'forecast_value_2025_07', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_07_forecast_id_idx', 'forecast_value_2025_07', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_07_target_time_idx', 'forecast_value_2025_07', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_08',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_08_created_utc_idx', 'forecast_value_2025_08', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_08_forecast_id_idx', 'forecast_value_2025_08', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_08_target_time_idx', 'forecast_value_2025_08', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_09',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_09_created_utc_idx', 'forecast_value_2025_09', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_09_forecast_id_idx', 'forecast_value_2025_09', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_09_target_time_idx', 'forecast_value_2025_09', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_10',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_10_created_utc_idx', 'forecast_value_2025_10', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_10_forecast_id_idx', 'forecast_value_2025_10', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_10_target_time_idx', 'forecast_value_2025_10', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_11',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_11_created_utc_idx', 'forecast_value_2025_11', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_11_forecast_id_idx', 'forecast_value_2025_11', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_11_target_time_idx', 'forecast_value_2025_11', ['target_time'], unique=False)
    op.create_table('forecast_value_2025_12',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2025_12_created_utc_idx', 'forecast_value_2025_12', ['created_utc'], unique=False)
    op.create_index('forecast_value_2025_12_forecast_id_idx', 'forecast_value_2025_12', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2025_12_target_time_idx', 'forecast_value_2025_12', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_01',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_01_created_utc_idx', 'forecast_value_2026_01', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_01_forecast_id_idx', 'forecast_value_2026_01', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_01_target_time_idx', 'forecast_value_2026_01', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_02',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_02_created_utc_idx', 'forecast_value_2026_02', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_02_forecast_id_idx', 'forecast_value_2026_02', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_02_target_time_idx', 'forecast_value_2026_02', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_03',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_03_created_utc_idx', 'forecast_value_2026_03', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_03_forecast_id_idx', 'forecast_value_2026_03', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_03_target_time_idx', 'forecast_value_2026_03', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_04',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_04_created_utc_idx', 'forecast_value_2026_04', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_04_forecast_id_idx', 'forecast_value_2026_04', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_04_target_time_idx', 'forecast_value_2026_04', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_05',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_05_created_utc_idx', 'forecast_value_2026_05', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_05_forecast_id_idx', 'forecast_value_2026_05', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_05_target_time_idx', 'forecast_value_2026_05', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_06',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_06_created_utc_idx', 'forecast_value_2026_06', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_06_forecast_id_idx', 'forecast_value_2026_06', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_06_target_time_idx', 'forecast_value_2026_06', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_07',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_07_created_utc_idx', 'forecast_value_2026_07', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_07_forecast_id_idx', 'forecast_value_2026_07', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_07_target_time_idx', 'forecast_value_2026_07', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_08',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_08_created_utc_idx', 'forecast_value_2026_08', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_08_forecast_id_idx', 'forecast_value_2026_08', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_08_target_time_idx', 'forecast_value_2026_08', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_09',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_09_created_utc_idx', 'forecast_value_2026_09', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_09_forecast_id_idx', 'forecast_value_2026_09', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_09_target_time_idx', 'forecast_value_2026_09', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_10',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_10_created_utc_idx', 'forecast_value_2026_10', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_10_forecast_id_idx', 'forecast_value_2026_10', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_10_target_time_idx', 'forecast_value_2026_10', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_11',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_11_created_utc_idx', 'forecast_value_2026_11', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_11_forecast_id_idx', 'forecast_value_2026_11', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_11_target_time_idx', 'forecast_value_2026_11', ['target_time'], unique=False)
    op.create_table('forecast_value_2026_12',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2026_12_created_utc_idx', 'forecast_value_2026_12', ['created_utc'], unique=False)
    op.create_index('forecast_value_2026_12_forecast_id_idx', 'forecast_value_2026_12', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2026_12_target_time_idx', 'forecast_value_2026_12', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_01',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_01_created_utc_idx', 'forecast_value_2027_01', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_01_forecast_id_idx', 'forecast_value_2027_01', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_01_target_time_idx', 'forecast_value_2027_01', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_02',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_02_created_utc_idx', 'forecast_value_2027_02', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_02_forecast_id_idx', 'forecast_value_2027_02', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_02_target_time_idx', 'forecast_value_2027_02', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_03',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_03_created_utc_idx', 'forecast_value_2027_03', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_03_forecast_id_idx', 'forecast_value_2027_03', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_03_target_time_idx', 'forecast_value_2027_03', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_04',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_04_created_utc_idx', 'forecast_value_2027_04', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_04_forecast_id_idx', 'forecast_value_2027_04', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_04_target_time_idx', 'forecast_value_2027_04', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_05',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_05_created_utc_idx', 'forecast_value_2027_05', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_05_forecast_id_idx', 'forecast_value_2027_05', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_05_target_time_idx', 'forecast_value_2027_05', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_06',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_06_created_utc_idx', 'forecast_value_2027_06', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_06_forecast_id_idx', 'forecast_value_2027_06', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_06_target_time_idx', 'forecast_value_2027_06', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_07',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_07_created_utc_idx', 'forecast_value_2027_07', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_07_forecast_id_idx', 'forecast_value_2027_07', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_07_target_time_idx', 'forecast_value_2027_07', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_08',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_08_created_utc_idx', 'forecast_value_2027_08', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_08_forecast_id_idx', 'forecast_value_2027_08', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_08_target_time_idx', 'forecast_value_2027_08', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_09',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_09_created_utc_idx', 'forecast_value_2027_09', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_09_forecast_id_idx', 'forecast_value_2027_09', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_09_target_time_idx', 'forecast_value_2027_09', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_10',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_10_created_utc_idx', 'forecast_value_2027_10', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_10_forecast_id_idx', 'forecast_value_2027_10', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_10_target_time_idx', 'forecast_value_2027_10', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_11',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_11_created_utc_idx', 'forecast_value_2027_11', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_11_forecast_id_idx', 'forecast_value_2027_11', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_11_target_time_idx', 'forecast_value_2027_11', ['target_time'], unique=False)
    op.create_table('forecast_value_2027_12',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2027_12_created_utc_idx', 'forecast_value_2027_12', ['created_utc'], unique=False)
    op.create_index('forecast_value_2027_12_forecast_id_idx', 'forecast_value_2027_12', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2027_12_target_time_idx', 'forecast_value_2027_12', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_01',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_01_created_utc_idx', 'forecast_value_2028_01', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_01_forecast_id_idx', 'forecast_value_2028_01', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_01_target_time_idx', 'forecast_value_2028_01', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_02',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_02_created_utc_idx', 'forecast_value_2028_02', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_02_forecast_id_idx', 'forecast_value_2028_02', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_02_target_time_idx', 'forecast_value_2028_02', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_03',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_03_created_utc_idx', 'forecast_value_2028_03', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_03_forecast_id_idx', 'forecast_value_2028_03', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_03_target_time_idx', 'forecast_value_2028_03', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_04',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_04_created_utc_idx', 'forecast_value_2028_04', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_04_forecast_id_idx', 'forecast_value_2028_04', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_04_target_time_idx', 'forecast_value_2028_04', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_05',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_05_created_utc_idx', 'forecast_value_2028_05', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_05_forecast_id_idx', 'forecast_value_2028_05', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_05_target_time_idx', 'forecast_value_2028_05', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_06',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_06_created_utc_idx', 'forecast_value_2028_06', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_06_forecast_id_idx', 'forecast_value_2028_06', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_06_target_time_idx', 'forecast_value_2028_06', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_07',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_07_created_utc_idx', 'forecast_value_2028_07', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_07_forecast_id_idx', 'forecast_value_2028_07', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_07_target_time_idx', 'forecast_value_2028_07', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_08',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_08_created_utc_idx', 'forecast_value_2028_08', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_08_forecast_id_idx', 'forecast_value_2028_08', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_08_target_time_idx', 'forecast_value_2028_08', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_09',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_09_created_utc_idx', 'forecast_value_2028_09', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_09_forecast_id_idx', 'forecast_value_2028_09', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_09_target_time_idx', 'forecast_value_2028_09', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_10',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_10_created_utc_idx', 'forecast_value_2028_10', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_10_forecast_id_idx', 'forecast_value_2028_10', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_10_target_time_idx', 'forecast_value_2028_10', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_11',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_11_created_utc_idx', 'forecast_value_2028_11', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_11_forecast_id_idx', 'forecast_value_2028_11', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_11_target_time_idx', 'forecast_value_2028_11', ['target_time'], unique=False)
    op.create_table('forecast_value_2028_12',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2028_12_created_utc_idx', 'forecast_value_2028_12', ['created_utc'], unique=False)
    op.create_index('forecast_value_2028_12_forecast_id_idx', 'forecast_value_2028_12', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2028_12_target_time_idx', 'forecast_value_2028_12', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_01',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_01_created_utc_idx', 'forecast_value_2029_01', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_01_forecast_id_idx', 'forecast_value_2029_01', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_01_target_time_idx', 'forecast_value_2029_01', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_02',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_02_created_utc_idx', 'forecast_value_2029_02', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_02_forecast_id_idx', 'forecast_value_2029_02', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_02_target_time_idx', 'forecast_value_2029_02', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_03',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_03_created_utc_idx', 'forecast_value_2029_03', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_03_forecast_id_idx', 'forecast_value_2029_03', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_03_target_time_idx', 'forecast_value_2029_03', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_04',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_04_created_utc_idx', 'forecast_value_2029_04', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_04_forecast_id_idx', 'forecast_value_2029_04', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_04_target_time_idx', 'forecast_value_2029_04', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_05',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_05_created_utc_idx', 'forecast_value_2029_05', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_05_forecast_id_idx', 'forecast_value_2029_05', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_05_target_time_idx', 'forecast_value_2029_05', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_06',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_06_created_utc_idx', 'forecast_value_2029_06', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_06_forecast_id_idx', 'forecast_value_2029_06', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_06_target_time_idx', 'forecast_value_2029_06', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_07',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_07_created_utc_idx', 'forecast_value_2029_07', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_07_forecast_id_idx', 'forecast_value_2029_07', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_07_target_time_idx', 'forecast_value_2029_07', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_08',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_08_created_utc_idx', 'forecast_value_2029_08', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_08_forecast_id_idx', 'forecast_value_2029_08', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_08_target_time_idx', 'forecast_value_2029_08', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_09',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_09_created_utc_idx', 'forecast_value_2029_09', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_09_forecast_id_idx', 'forecast_value_2029_09', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_09_target_time_idx', 'forecast_value_2029_09', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_10',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_10_created_utc_idx', 'forecast_value_2029_10', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_10_forecast_id_idx', 'forecast_value_2029_10', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_10_target_time_idx', 'forecast_value_2029_10', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_11',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_11_created_utc_idx', 'forecast_value_2029_11', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_11_forecast_id_idx', 'forecast_value_2029_11', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_11_target_time_idx', 'forecast_value_2029_11', ['target_time'], unique=False)
    op.create_table('forecast_value_2029_12',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_generation_megawatts', sa.Float(), nullable=True),
    sa.Column('adjust_mw', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.PrimaryKeyConstraint('uuid', 'target_time')
    )
    op.create_index('forecast_value_2029_12_created_utc_idx', 'forecast_value_2029_12', ['created_utc'], unique=False)
    op.create_index('forecast_value_2029_12_forecast_id_idx', 'forecast_value_2029_12', ['forecast_id'], unique=False)
    op.create_index('forecast_value_2029_12_target_time_idx', 'forecast_value_2029_12', ['target_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrades the database schema to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('forecast_value_2029_12_target_time_idx', table_name='forecast_value_2029_12')
    op.drop_index('forecast_value_2029_12_forecast_id_idx', table_name='forecast_value_2029_12')
    op.drop_index('forecast_value_2029_12_created_utc_idx', table_name='forecast_value_2029_12')
    op.drop_table('forecast_value_2029_12')
    op.drop_index('forecast_value_2029_11_target_time_idx', table_name='forecast_value_2029_11')
    op.drop_index('forecast_value_2029_11_forecast_id_idx', table_name='forecast_value_2029_11')
    op.drop_index('forecast_value_2029_11_created_utc_idx', table_name='forecast_value_2029_11')
    op.drop_table('forecast_value_2029_11')
    op.drop_index('forecast_value_2029_10_target_time_idx', table_name='forecast_value_2029_10')
    op.drop_index('forecast_value_2029_10_forecast_id_idx', table_name='forecast_value_2029_10')
    op.drop_index('forecast_value_2029_10_created_utc_idx', table_name='forecast_value_2029_10')
    op.drop_table('forecast_value_2029_10')
    op.drop_index('forecast_value_2029_09_target_time_idx', table_name='forecast_value_2029_09')
    op.drop_index('forecast_value_2029_09_forecast_id_idx', table_name='forecast_value_2029_09')
    op.drop_index('forecast_value_2029_09_created_utc_idx', table_name='forecast_value_2029_09')
    op.drop_table('forecast_value_2029_09')
    op.drop_index('forecast_value_2029_08_target_time_idx', table_name='forecast_value_2029_08')
    op.drop_index('forecast_value_2029_08_forecast_id_idx', table_name='forecast_value_2029_08')
    op.drop_index('forecast_value_2029_08_created_utc_idx', table_name='forecast_value_2029_08')
    op.drop_table('forecast_value_2029_08')
    op.drop_index('forecast_value_2029_07_target_time_idx', table_name='forecast_value_2029_07')
    op.drop_index('forecast_value_2029_07_forecast_id_idx', table_name='forecast_value_2029_07')
    op.drop_index('forecast_value_2029_07_created_utc_idx', table_name='forecast_value_2029_07')
    op.drop_table('forecast_value_2029_07')
    op.drop_index('forecast_value_2029_06_target_time_idx', table_name='forecast_value_2029_06')
    op.drop_index('forecast_value_2029_06_forecast_id_idx', table_name='forecast_value_2029_06')
    op.drop_index('forecast_value_2029_06_created_utc_idx', table_name='forecast_value_2029_06')
    op.drop_table('forecast_value_2029_06')
    op.drop_index('forecast_value_2029_05_target_time_idx', table_name='forecast_value_2029_05')
    op.drop_index('forecast_value_2029_05_forecast_id_idx', table_name='forecast_value_2029_05')
    op.drop_index('forecast_value_2029_05_created_utc_idx', table_name='forecast_value_2029_05')
    op.drop_table('forecast_value_2029_05')
    op.drop_index('forecast_value_2029_04_target_time_idx', table_name='forecast_value_2029_04')
    op.drop_index('forecast_value_2029_04_forecast_id_idx', table_name='forecast_value_2029_04')
    op.drop_index('forecast_value_2029_04_created_utc_idx', table_name='forecast_value_2029_04')
    op.drop_table('forecast_value_2029_04')
    op.drop_index('forecast_value_2029_03_target_time_idx', table_name='forecast_value_2029_03')
    op.drop_index('forecast_value_2029_03_forecast_id_idx', table_name='forecast_value_2029_03')
    op.drop_index('forecast_value_2029_03_created_utc_idx', table_name='forecast_value_2029_03')
    op.drop_table('forecast_value_2029_03')
    op.drop_index('forecast_value_2029_02_target_time_idx', table_name='forecast_value_2029_02')
    op.drop_index('forecast_value_2029_02_forecast_id_idx', table_name='forecast_value_2029_02')
    op.drop_index('forecast_value_2029_02_created_utc_idx', table_name='forecast_value_2029_02')
    op.drop_table('forecast_value_2029_02')
    op.drop_index('forecast_value_2029_01_target_time_idx', table_name='forecast_value_2029_01')
    op.drop_index('forecast_value_2029_01_forecast_id_idx', table_name='forecast_value_2029_01')
    op.drop_index('forecast_value_2029_01_created_utc_idx', table_name='forecast_value_2029_01')
    op.drop_table('forecast_value_2029_01')
    op.drop_index('forecast_value_2028_12_target_time_idx', table_name='forecast_value_2028_12')
    op.drop_index('forecast_value_2028_12_forecast_id_idx', table_name='forecast_value_2028_12')
    op.drop_index('forecast_value_2028_12_created_utc_idx', table_name='forecast_value_2028_12')
    op.drop_table('forecast_value_2028_12')
    op.drop_index('forecast_value_2028_11_target_time_idx', table_name='forecast_value_2028_11')
    op.drop_index('forecast_value_2028_11_forecast_id_idx', table_name='forecast_value_2028_11')
    op.drop_index('forecast_value_2028_11_created_utc_idx', table_name='forecast_value_2028_11')
    op.drop_table('forecast_value_2028_11')
    op.drop_index('forecast_value_2028_10_target_time_idx', table_name='forecast_value_2028_10')
    op.drop_index('forecast_value_2028_10_forecast_id_idx', table_name='forecast_value_2028_10')
    op.drop_index('forecast_value_2028_10_created_utc_idx', table_name='forecast_value_2028_10')
    op.drop_table('forecast_value_2028_10')
    op.drop_index('forecast_value_2028_09_target_time_idx', table_name='forecast_value_2028_09')
    op.drop_index('forecast_value_2028_09_forecast_id_idx', table_name='forecast_value_2028_09')
    op.drop_index('forecast_value_2028_09_created_utc_idx', table_name='forecast_value_2028_09')
    op.drop_table('forecast_value_2028_09')
    op.drop_index('forecast_value_2028_08_target_time_idx', table_name='forecast_value_2028_08')
    op.drop_index('forecast_value_2028_08_forecast_id_idx', table_name='forecast_value_2028_08')
    op.drop_index('forecast_value_2028_08_created_utc_idx', table_name='forecast_value_2028_08')
    op.drop_table('forecast_value_2028_08')
    op.drop_index('forecast_value_2028_07_target_time_idx', table_name='forecast_value_2028_07')
    op.drop_index('forecast_value_2028_07_forecast_id_idx', table_name='forecast_value_2028_07')
    op.drop_index('forecast_value_2028_07_created_utc_idx', table_name='forecast_value_2028_07')
    op.drop_table('forecast_value_2028_07')
    op.drop_index('forecast_value_2028_06_target_time_idx', table_name='forecast_value_2028_06')
    op.drop_index('forecast_value_2028_06_forecast_id_idx', table_name='forecast_value_2028_06')
    op.drop_index('forecast_value_2028_06_created_utc_idx', table_name='forecast_value_2028_06')
    op.drop_table('forecast_value_2028_06')
    op.drop_index('forecast_value_2028_05_target_time_idx', table_name='forecast_value_2028_05')
    op.drop_index('forecast_value_2028_05_forecast_id_idx', table_name='forecast_value_2028_05')
    op.drop_index('forecast_value_2028_05_created_utc_idx', table_name='forecast_value_2028_05')
    op.drop_table('forecast_value_2028_05')
    op.drop_index('forecast_value_2028_04_target_time_idx', table_name='forecast_value_2028_04')
    op.drop_index('forecast_value_2028_04_forecast_id_idx', table_name='forecast_value_2028_04')
    op.drop_index('forecast_value_2028_04_created_utc_idx', table_name='forecast_value_2028_04')
    op.drop_table('forecast_value_2028_04')
    op.drop_index('forecast_value_2028_03_target_time_idx', table_name='forecast_value_2028_03')
    op.drop_index('forecast_value_2028_03_forecast_id_idx', table_name='forecast_value_2028_03')
    op.drop_index('forecast_value_2028_03_created_utc_idx', table_name='forecast_value_2028_03')
    op.drop_table('forecast_value_2028_03')
    op.drop_index('forecast_value_2028_02_target_time_idx', table_name='forecast_value_2028_02')
    op.drop_index('forecast_value_2028_02_forecast_id_idx', table_name='forecast_value_2028_02')
    op.drop_index('forecast_value_2028_02_created_utc_idx', table_name='forecast_value_2028_02')
    op.drop_table('forecast_value_2028_02')
    op.drop_index('forecast_value_2028_01_target_time_idx', table_name='forecast_value_2028_01')
    op.drop_index('forecast_value_2028_01_forecast_id_idx', table_name='forecast_value_2028_01')
    op.drop_index('forecast_value_2028_01_created_utc_idx', table_name='forecast_value_2028_01')
    op.drop_table('forecast_value_2028_01')
    op.drop_index('forecast_value_2027_12_target_time_idx', table_name='forecast_value_2027_12')
    op.drop_index('forecast_value_2027_12_forecast_id_idx', table_name='forecast_value_2027_12')
    op.drop_index('forecast_value_2027_12_created_utc_idx', table_name='forecast_value_2027_12')
    op.drop_table('forecast_value_2027_12')
    op.drop_index('forecast_value_2027_11_target_time_idx', table_name='forecast_value_2027_11')
    op.drop_index('forecast_value_2027_11_forecast_id_idx', table_name='forecast_value_2027_11')
    op.drop_index('forecast_value_2027_11_created_utc_idx', table_name='forecast_value_2027_11')
    op.drop_table('forecast_value_2027_11')
    op.drop_index('forecast_value_2027_10_target_time_idx', table_name='forecast_value_2027_10')
    op.drop_index('forecast_value_2027_10_forecast_id_idx', table_name='forecast_value_2027_10')
    op.drop_index('forecast_value_2027_10_created_utc_idx', table_name='forecast_value_2027_10')
    op.drop_table('forecast_value_2027_10')
    op.drop_index('forecast_value_2027_09_target_time_idx', table_name='forecast_value_2027_09')
    op.drop_index('forecast_value_2027_09_forecast_id_idx', table_name='forecast_value_2027_09')
    op.drop_index('forecast_value_2027_09_created_utc_idx', table_name='forecast_value_2027_09')
    op.drop_table('forecast_value_2027_09')
    op.drop_index('forecast_value_2027_08_target_time_idx', table_name='forecast_value_2027_08')
    op.drop_index('forecast_value_2027_08_forecast_id_idx', table_name='forecast_value_2027_08')
    op.drop_index('forecast_value_2027_08_created_utc_idx', table_name='forecast_value_2027_08')
    op.drop_table('forecast_value_2027_08')
    op.drop_index('forecast_value_2027_07_target_time_idx', table_name='forecast_value_2027_07')
    op.drop_index('forecast_value_2027_07_forecast_id_idx', table_name='forecast_value_2027_07')
    op.drop_index('forecast_value_2027_07_created_utc_idx', table_name='forecast_value_2027_07')
    op.drop_table('forecast_value_2027_07')
    op.drop_index('forecast_value_2027_06_target_time_idx', table_name='forecast_value_2027_06')
    op.drop_index('forecast_value_2027_06_forecast_id_idx', table_name='forecast_value_2027_06')
    op.drop_index('forecast_value_2027_06_created_utc_idx', table_name='forecast_value_2027_06')
    op.drop_table('forecast_value_2027_06')
    op.drop_index('forecast_value_2027_05_target_time_idx', table_name='forecast_value_2027_05')
    op.drop_index('forecast_value_2027_05_forecast_id_idx', table_name='forecast_value_2027_05')
    op.drop_index('forecast_value_2027_05_created_utc_idx', table_name='forecast_value_2027_05')
    op.drop_table('forecast_value_2027_05')
    op.drop_index('forecast_value_2027_04_target_time_idx', table_name='forecast_value_2027_04')
    op.drop_index('forecast_value_2027_04_forecast_id_idx', table_name='forecast_value_2027_04')
    op.drop_index('forecast_value_2027_04_created_utc_idx', table_name='forecast_value_2027_04')
    op.drop_table('forecast_value_2027_04')
    op.drop_index('forecast_value_2027_03_target_time_idx', table_name='forecast_value_2027_03')
    op.drop_index('forecast_value_2027_03_forecast_id_idx', table_name='forecast_value_2027_03')
    op.drop_index('forecast_value_2027_03_created_utc_idx', table_name='forecast_value_2027_03')
    op.drop_table('forecast_value_2027_03')
    op.drop_index('forecast_value_2027_02_target_time_idx', table_name='forecast_value_2027_02')
    op.drop_index('forecast_value_2027_02_forecast_id_idx', table_name='forecast_value_2027_02')
    op.drop_index('forecast_value_2027_02_created_utc_idx', table_name='forecast_value_2027_02')
    op.drop_table('forecast_value_2027_02')
    op.drop_index('forecast_value_2027_01_target_time_idx', table_name='forecast_value_2027_01')
    op.drop_index('forecast_value_2027_01_forecast_id_idx', table_name='forecast_value_2027_01')
    op.drop_index('forecast_value_2027_01_created_utc_idx', table_name='forecast_value_2027_01')
    op.drop_table('forecast_value_2027_01')
    op.drop_index('forecast_value_2026_12_target_time_idx', table_name='forecast_value_2026_12')
    op.drop_index('forecast_value_2026_12_forecast_id_idx', table_name='forecast_value_2026_12')
    op.drop_index('forecast_value_2026_12_created_utc_idx', table_name='forecast_value_2026_12')
    op.drop_table('forecast_value_2026_12')
    op.drop_index('forecast_value_2026_11_target_time_idx', table_name='forecast_value_2026_11')
    op.drop_index('forecast_value_2026_11_forecast_id_idx', table_name='forecast_value_2026_11')
    op.drop_index('forecast_value_2026_11_created_utc_idx', table_name='forecast_value_2026_11')
    op.drop_table('forecast_value_2026_11')
    op.drop_index('forecast_value_2026_10_target_time_idx', table_name='forecast_value_2026_10')
    op.drop_index('forecast_value_2026_10_forecast_id_idx', table_name='forecast_value_2026_10')
    op.drop_index('forecast_value_2026_10_created_utc_idx', table_name='forecast_value_2026_10')
    op.drop_table('forecast_value_2026_10')
    op.drop_index('forecast_value_2026_09_target_time_idx', table_name='forecast_value_2026_09')
    op.drop_index('forecast_value_2026_09_forecast_id_idx', table_name='forecast_value_2026_09')
    op.drop_index('forecast_value_2026_09_created_utc_idx', table_name='forecast_value_2026_09')
    op.drop_table('forecast_value_2026_09')
    op.drop_index('forecast_value_2026_08_target_time_idx', table_name='forecast_value_2026_08')
    op.drop_index('forecast_value_2026_08_forecast_id_idx', table_name='forecast_value_2026_08')
    op.drop_index('forecast_value_2026_08_created_utc_idx', table_name='forecast_value_2026_08')
    op.drop_table('forecast_value_2026_08')
    op.drop_index('forecast_value_2026_07_target_time_idx', table_name='forecast_value_2026_07')
    op.drop_index('forecast_value_2026_07_forecast_id_idx', table_name='forecast_value_2026_07')
    op.drop_index('forecast_value_2026_07_created_utc_idx', table_name='forecast_value_2026_07')
    op.drop_table('forecast_value_2026_07')
    op.drop_index('forecast_value_2026_06_target_time_idx', table_name='forecast_value_2026_06')
    op.drop_index('forecast_value_2026_06_forecast_id_idx', table_name='forecast_value_2026_06')
    op.drop_index('forecast_value_2026_06_created_utc_idx', table_name='forecast_value_2026_06')
    op.drop_table('forecast_value_2026_06')
    op.drop_index('forecast_value_2026_05_target_time_idx', table_name='forecast_value_2026_05')
    op.drop_index('forecast_value_2026_05_forecast_id_idx', table_name='forecast_value_2026_05')
    op.drop_index('forecast_value_2026_05_created_utc_idx', table_name='forecast_value_2026_05')
    op.drop_table('forecast_value_2026_05')
    op.drop_index('forecast_value_2026_04_target_time_idx', table_name='forecast_value_2026_04')
    op.drop_index('forecast_value_2026_04_forecast_id_idx', table_name='forecast_value_2026_04')
    op.drop_index('forecast_value_2026_04_created_utc_idx', table_name='forecast_value_2026_04')
    op.drop_table('forecast_value_2026_04')
    op.drop_index('forecast_value_2026_03_target_time_idx', table_name='forecast_value_2026_03')
    op.drop_index('forecast_value_2026_03_forecast_id_idx', table_name='forecast_value_2026_03')
    op.drop_index('forecast_value_2026_03_created_utc_idx', table_name='forecast_value_2026_03')
    op.drop_table('forecast_value_2026_03')
    op.drop_index('forecast_value_2026_02_target_time_idx', table_name='forecast_value_2026_02')
    op.drop_index('forecast_value_2026_02_forecast_id_idx', table_name='forecast_value_2026_02')
    op.drop_index('forecast_value_2026_02_created_utc_idx', table_name='forecast_value_2026_02')
    op.drop_table('forecast_value_2026_02')
    op.drop_index('forecast_value_2026_01_target_time_idx', table_name='forecast_value_2026_01')
    op.drop_index('forecast_value_2026_01_forecast_id_idx', table_name='forecast_value_2026_01')
    op.drop_index('forecast_value_2026_01_created_utc_idx', table_name='forecast_value_2026_01')
    op.drop_table('forecast_value_2026_01')
    op.drop_index('forecast_value_2025_12_target_time_idx', table_name='forecast_value_2025_12')
    op.drop_index('forecast_value_2025_12_forecast_id_idx', table_name='forecast_value_2025_12')
    op.drop_index('forecast_value_2025_12_created_utc_idx', table_name='forecast_value_2025_12')
    op.drop_table('forecast_value_2025_12')
    op.drop_index('forecast_value_2025_11_target_time_idx', table_name='forecast_value_2025_11')
    op.drop_index('forecast_value_2025_11_forecast_id_idx', table_name='forecast_value_2025_11')
    op.drop_index('forecast_value_2025_11_created_utc_idx', table_name='forecast_value_2025_11')
    op.drop_table('forecast_value_2025_11')
    op.drop_index('forecast_value_2025_10_target_time_idx', table_name='forecast_value_2025_10')
    op.drop_index('forecast_value_2025_10_forecast_id_idx', table_name='forecast_value_2025_10')
    op.drop_index('forecast_value_2025_10_created_utc_idx', table_name='forecast_value_2025_10')
    op.drop_table('forecast_value_2025_10')
    op.drop_index('forecast_value_2025_09_target_time_idx', table_name='forecast_value_2025_09')
    op.drop_index('forecast_value_2025_09_forecast_id_idx', table_name='forecast_value_2025_09')
    op.drop_index('forecast_value_2025_09_created_utc_idx', table_name='forecast_value_2025_09')
    op.drop_table('forecast_value_2025_09')
    op.drop_index('forecast_value_2025_08_target_time_idx', table_name='forecast_value_2025_08')
    op.drop_index('forecast_value_2025_08_forecast_id_idx', table_name='forecast_value_2025_08')
    op.drop_index('forecast_value_2025_08_created_utc_idx', table_name='forecast_value_2025_08')
    op.drop_table('forecast_value_2025_08')
    op.drop_index('forecast_value_2025_07_target_time_idx', table_name='forecast_value_2025_07')
    op.drop_index('forecast_value_2025_07_forecast_id_idx', table_name='forecast_value_2025_07')
    op.drop_index('forecast_value_2025_07_created_utc_idx', table_name='forecast_value_2025_07')
    op.drop_table('forecast_value_2025_07')
    op.drop_index('forecast_value_2025_06_target_time_idx', table_name='forecast_value_2025_06')
    op.drop_index('forecast_value_2025_06_forecast_id_idx', table_name='forecast_value_2025_06')
    op.drop_index('forecast_value_2025_06_created_utc_idx', table_name='forecast_value_2025_06')
    op.drop_table('forecast_value_2025_06')
    op.drop_index('forecast_value_2025_05_target_time_idx', table_name='forecast_value_2025_05')
    op.drop_index('forecast_value_2025_05_forecast_id_idx', table_name='forecast_value_2025_05')
    op.drop_index('forecast_value_2025_05_created_utc_idx', table_name='forecast_value_2025_05')
    op.drop_table('forecast_value_2025_05')
    op.drop_index('forecast_value_2025_04_target_time_idx', table_name='forecast_value_2025_04')
    op.drop_index('forecast_value_2025_04_forecast_id_idx', table_name='forecast_value_2025_04')
    op.drop_index('forecast_value_2025_04_created_utc_idx', table_name='forecast_value_2025_04')
    op.drop_table('forecast_value_2025_04')
    op.drop_index('forecast_value_2025_03_target_time_idx', table_name='forecast_value_2025_03')
    op.drop_index('forecast_value_2025_03_forecast_id_idx', table_name='forecast_value_2025_03')
    op.drop_index('forecast_value_2025_03_created_utc_idx', table_name='forecast_value_2025_03')
    op.drop_table('forecast_value_2025_03')
    op.drop_index('forecast_value_2025_02_target_time_idx', table_name='forecast_value_2025_02')
    op.drop_index('forecast_value_2025_02_forecast_id_idx', table_name='forecast_value_2025_02')
    op.drop_index('forecast_value_2025_02_created_utc_idx', table_name='forecast_value_2025_02')
    op.drop_table('forecast_value_2025_02')
    op.drop_index('forecast_value_2025_01_target_time_idx', table_name='forecast_value_2025_01')
    op.drop_index('forecast_value_2025_01_forecast_id_idx', table_name='forecast_value_2025_01')
    op.drop_index('forecast_value_2025_01_created_utc_idx', table_name='forecast_value_2025_01')
    op.drop_table('forecast_value_2025_01')
    # ### end Alembic commands ###
