""" Add created_utc index

This migrations takes about 5 minutes to run

Revision ID: ed4a2f8c030a
Revises: a6fb75892950
Create Date: 2023-09-07 12:55:37.559371

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed4a2f8c030a"
down_revision = "a6fb75892950"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_datetime_interval_end_datetime_utc", table_name="datetime_interval")
    op.create_index(
        op.f("ix_datetime_interval_end_datetime_utc"),
        "datetime_interval",
        ["end_datetime_utc"],
        unique=False,
    )
    op.drop_index("ix_datetime_interval_start_datetime_utc", table_name="datetime_interval")
    op.create_index(
        op.f("ix_datetime_interval_start_datetime_utc"),
        "datetime_interval",
        ["start_datetime_utc"],
        unique=False,
    )
    op.create_index("idx_forecast_created_utc", "forecast", ["created_utc"], unique=False)
    op.create_index("index_forecast_historic", "forecast", ["historic"], unique=False)
    op.create_index(
        "ix_forecast_created_utc", "forecast", [sa.text("created_utc DESC")], unique=False
    )
    op.create_index(
        "ix_forecast_value_created_utc", "forecast_value", ["created_utc"], unique=False
    )
    op.create_index(
        "ix_forecast_value_seven_days_created_utc",
        "forecast_value_last_seven_days",
        [sa.text("created_utc DESC")],
        unique=False,
    )
    op.create_index(
        "ix_forecast_value_latest_created_utc",
        "forecast_value_latest",
        [sa.text("created_utc DESC")],
        unique=False,
    )
    op.create_index(
        "ix_gsp_yield_created_utc", "gsp_yield", [sa.text("created_utc DESC")], unique=False
    )
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gsp_yield_created_utc", table_name="gsp_yield")
    op.drop_index("ix_forecast_value_latest_created_utc", table_name="forecast_value_latest")
    op.drop_index(
        "ix_forecast_value_seven_days_created_utc", table_name="forecast_value_last_seven_days"
    )
    op.drop_index("ix_forecast_value_created_utc", table_name="forecast_value")
    op.drop_index("ix_forecast_created_utc", table_name="forecast")
    op.drop_index("index_forecast_historic", table_name="forecast")
    op.drop_index("idx_forecast_created_utc", table_name="forecast")
    op.drop_index(op.f("ix_datetime_interval_start_datetime_utc"), table_name="datetime_interval")
    op.create_index(
        "ix_datetime_interval_start_datetime_utc",
        "datetime_interval",
        [sa.text("start_datetime_utc DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_datetime_interval_end_datetime_utc"), table_name="datetime_interval")
    op.create_index(
        "ix_datetime_interval_end_datetime_utc",
        "datetime_interval",
        [sa.text("end_datetime_utc DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
