"""empty message

Revision ID: 580416fad3df
Revises: 
Create Date: 2022-03-11 13:39:18.848072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580416fad3df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pv_system',
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pv_system_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('orientation', sa.Float(), nullable=True),
    sa.Column('status_interval_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pv_system_pv_system_id'), 'pv_system', ['pv_system_id'], unique=False)
    op.create_table('pv_yield',
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=True),
    sa.Column('solar_generation_kw', sa.String(), nullable=True),
    sa.Column('pv_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pv_system_id'], ['pv_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pv_yield_datetime_utc'), 'pv_yield', ['datetime_utc'], unique=False)
    op.create_index(op.f('ix_pv_yield_pv_system_id'), 'pv_yield', ['pv_system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pv_yield_pv_system_id'), table_name='pv_yield')
    op.drop_index(op.f('ix_pv_yield_datetime_utc'), table_name='pv_yield')
    op.drop_table('pv_yield')
    op.drop_index(op.f('ix_pv_system_pv_system_id'), table_name='pv_system')
    op.drop_table('pv_system')
    # ### end Alembic commands ###
