""" Add ml capacity to pv system

Revision ID: 7190d7adc63f
Revises: c061c49cbf37
Create Date: 2022-07-07 10:37:57.733009

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7190d7adc63f"
down_revision = "c061c49cbf37"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pv_system", sa.Column("ml_capacity_kw", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_system", "ml_capacity_kw")
    # ### end Alembic commands ###
