"""change installed capacity to float

Revision ID: ade0a67b3567
Revises: e1dd779648d2
Create Date: 2022-05-20 10:36:41.016224

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ade0a67b3567"
down_revision = "e1dd779648d2"
branch_labels = None
depends_on = None


def upgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pv_system", sa.Column("installed_capacity_kw", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_system", "installed_capacity_kw")
    # ### end Alembic commands ###
