""" Add PV index (desc)

Revision ID: e1dd779648d2
Revises: 580416fad3df
Create Date: 2022-03-21 09:05:41.512769

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1dd779648d2"
down_revision = "580416fad3df"
branch_labels = None
depends_on = None


def upgrade():  # noqa 103
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_datetime_utc", "pv_yield", [sa.text("datetime_utc DESC")], unique=False)
    # ### end Alembic commands ###


def downgrade():  # noqa 103
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_datetime_utc", table_name="pv_yield")
    # ### end Alembic commands ###
